name: ci
on:
  push:
    branches:
      - main
jobs:
  example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup example
        run: |
          mkdir -p example/.fluentci
          cp -r src example/.fluentci
          cp Cargo.toml example/.fluentci
          cp Cargo.lock example/.fluentci
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            get kind
          working-directory: example
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Firecracker
        if: runner.os == 'ubuntu-latest'
        run: |
          fluentci run --wasm . system install firecracker
          type firecracker
          firecracker --version
        working-directory: example
      - name: Show arkade version
        run: |
          type arkade
          type kind
          kind version
          arkade version
